name: Build All Platforms

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    name: Windows Build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/**/*.exe

  macos:
    runs-on: macos-12
    name: macOS Build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - name: Upload macOS PKG
        uses: actions/upload-artifact@v4
        with:
          name: macos-pkg
          path: dist/**/*.pkg

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: dist/**/*.dmg

  linux:
    runs-on: ubuntu-latest
    name: Linux Build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: dist/**/*.deb

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: dist/**/*.AppImage
